export const types = Object.freeze({
    EMIT_ERROR:         'EMIT_ERROR',
    SHOW_NOTIFICATION:  'SHOW_NOTIFICATION',
    HIDE_NOTIFICATION:  'HIDE_NOTIFICATION',
    SET_ONLINE_STATE:   'SET_ONLINE_STATE',
    SET_FETCHING_STATE: 'SET_FETCHING_STATE',
});
